[package]
name = "duckdb"
version = "0.1.0"
authors = ["wangfenjin <wangfenj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["libduckdb-sys"]


[features]
bundled = ["libduckdb-sys/bundled"]
buildtime_bindgen = ["libduckdb-sys/buildtime_bindgen"]

[dependencies]

[dependencies.libduckdb-sys]
path = "libduckdb-sys"
version = "0.1.0"